---
version: 2

jobs:
  build:
    docker:
      - image: node
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ arch }}-
      - run:
          name: Install packages
          command: |
            apt-get update
            apt-get install -y rsync
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: npm-{{ arch }}-{{ epoch }}
          paths: ~/.npm
      - run:
          name: Test package
          command: npm test
      - run:
          name: Test Linux IO
          command: CURATOR_IO=linux npm test
      - deploy:
          name: Publish package
          command: |
            if [[ -n "${CIRCLE_TAG}" ]]; then
              echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
              npm publish
            else
              echo 'Nothing to publish: not a tag.'
            fi

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
